name: CI para Calculadora

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Atualizar pip e Instalar Semgrep
        run: |
          python -m pip install --upgrade pip
          python -m pip install semgrep

      - name: Rodar Semgrep
        run: semgrep --config=auto .

      - name: Gerar requirements.txt
        run: |
          echo "flask==2.3.3
          pytest==7.4.0
          requests==2.31.0
          python-dotenv==1.0.0
          gunicorn==21.2.0" > requirements.txt

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: pytest tests/

  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Semgrep
        run: |
          python -m pip install --upgrade pip
          python -m pip install semgrep

      - name: Executar Semgrep
        run: semgrep --config=auto .

  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciar aplicação Flask
        run: |
          nohup flask run --host=0.0.0.0 &
          sleep 10

      - name: Rodar OWASP ZAP
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
          -t http://localhost:5000 -r zap_report.html

      - name: Salvar relatório ZAP
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html

      - name: Upload artifact extra
        uses: actions/upload-artifact@v4
        with:
          name: meu-artifact
          path: caminho/do/arquivo-ou-pasta
