name: CI para Calculadora

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Rodar Semgrep
        run: semgrep --config=auto .
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerar requirements.txt
        run: |
          echo "flask==2.3.3
          pytest==7.4.0
          requests==2.31.0
          python-dotenv==1.0.0
          gunicorn==21.2.0" > requirements.txt

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: pytest tests/

  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Semgrep
        run: semgrep --config=auto .
